#!/bin/sh

set -e

# First, make sure we have a host key; there are multiple host key
# files, we just check that one of them exists.
if [ ! -e /etc/ssh/ssh_host_rsa_key ]; then
  # See if host keys have been defined in the repositories volume.
  HOSTKEY_DIR="/home/git/repositories/.ssh/host-keys"
  if [ -e "$HOSTKEY_DIR/ssh_host_rsa_key" ]; then
    echo "Using host key from $HOSTKEY_DIR"
    cp "$HOSTKEY_DIR"/* /etc/ssh/
  else
    echo "No SSH host keys available. Generating..."
    ssh-keygen -A
  fi
fi

cd /home/git

# If .ssh has been mounted, ensure it has the right permissions. Otherwise, an
# optional directory in the repositories volume can provide its contents.
if [ ! -d ./.ssh ]; then
  CLIENT_DIR="/home/git/repositories/.ssh/client"
  mkdir -p ./.ssh
  if [ -d "$CLIENT_DIR" ]; then
    echo "Copying files from $CLIENT_DIR to /home/git/.ssh"
    cp -pR "$CLIENT_DIR"/. ./.ssh/
  fi
fi
chown -R git:git ./.ssh
chmod 700 ./.ssh

# Always make sure the git user has a private key for mirroring setups etc.
if [ ! -f ./.ssh/id_rsa ]; then
  ssh-keygen -q -f /home/git/.ssh/id_rsa -t rsa -N ''
  echo "Here is the public key of the container's 'git' user:"
  cat /home/git/.ssh/id_rsa.pub
fi

# Support trusting hosts for mirroring setups.
if [ ! -f ./.ssh/known_hosts ] && [ -n "${TRUST_HOSTS:-}" ]; then
  echo "Generating known_hosts file with $TRUST_HOSTS"
  ssh-keyscan -H "$TRUST_HOSTS" > /home/git/.ssh/known_hosts
fi

if [ ! -d ./.gitolite ]; then
  # If there is an existing repositories/ folder, it must have been
  # bind-mounted; make sure it has the correct access permissions.
  if [ -d ./repositories ]; then
    chown -R git:git repositories
  fi

  # Gitolite needs to be set up.
  if [ -n "${SSH_KEY:-}" ]; then
    echo "Initializing gitolite, while authorizing your selected key for the admin repo"
    printf '%s\n' "$SSH_KEY" > /tmp/admin.pub
    bin/gitolite setup -pk /tmp/admin.pub
    rm /tmp/admin.pub
  else
    # If no SSH key is given, support bootstrapping from an existing
    # gitolite-admin repository.

    # gitolite setup adds a new commit to an existing gitolite-admin dir that
    # resets everything. Avoid that by renaming it first.
    if [ -d ./repositories/gitolite-admin.git ]; then
      mv ./repositories/gitolite-admin.git ./repositories/gitolite-admin.git-tmp
    fi

    # First set up Gitolite without an SSH key. This creates .gitolite and
    # .gitolite.rc without authorizing access to the generated admin repo.
    echo "Initializing gitolite without authorizing a key for accessing the admin repo"
    bin/gitolite setup -a dummy

    # Remove the gitolite-admin repo generated by setup.
    if [ -d ./repositories/gitolite-admin.git-tmp ]; then
      rm -rf ./repositories/gitolite-admin.git
      mv ./repositories/gitolite-admin.git-tmp ./repositories/gitolite-admin.git
    fi

    # Apply config customizations. We need to do this now because without the
    # right config the compile may fail.
    rcfile=/home/git/.gitolite.rc
    git_config_keys=$(printf '%s' "${GIT_CONFIG_KEYS:-}" | sed 's/[\\&|"]/\\&/g')
    sed -i "s|GIT_CONFIG_KEYS.*=>.*''|GIT_CONFIG_KEYS => \"${git_config_keys}\"|g" "$rcfile"
    if [ -n "${LOCAL_CODE:-}" ]; then
      local_code=$(printf '%s' "$LOCAL_CODE" | sed 's/[\\&|"]/\\&/g')
      sed -i "s|# LOCAL_CODE.*=>.*$|LOCAL_CODE => \"${local_code}\",|" "$rcfile"
    fi

    # Create a log directory to prevent CLI spew.
    mkdir -p .gitolite/logs
    # Set up hooks for the following post-update hook call.
    bin/gitolite setup --hooks-only

    # Update authorized_keys based on the gitolite-admin repo by triggering
    # its post-update hook. Use its configured HEAD rather than assuming
    # refs/heads/master (Gitolite v3.6.14+ supports non-master admin repos).
    admin_repo=/home/git/repositories/gitolite-admin.git
    admin_head=$(git -C "$admin_repo" symbolic-ref HEAD)
    GL_LIBDIR="$(/home/git/bin/gitolite query-rc GL_LIBDIR)" PATH="$PATH:/home/git/bin" \
      "$admin_repo/hooks/post-update" "$admin_head"
  fi
else
  # Resync on every restart.
  bin/gitolite setup
fi

# Allow specifying "sshd" as a command.
if [ "${1:-}" = 'sshd' ]; then
  set -- /usr/sbin/sshd -D -f /usr/local/etc/sshd_config
fi

echo "Executing $*"
exec "$@"
